# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180106_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='rate',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Provider'),
        ),
    ]
